In [46]:
import pandas as pd
import numpy as np

In [47]:
from google.colab import drive
drive.mount('gdrive/')

Drive already mounted at gdrive/; to attempt to forcibly remount, call drive.mount("gdrive/", force_remount=True).


In [48]:
df = pd.read_csv('/content/gdrive/MyDrive/enron_spam_data.csv')

In [49]:
df.head()

Message ID                       Subject  \
0           0  christmas tree farm pictures   
1           1      vastar resources , inc .   
2           2  calpine daily gas nomination   
3           3                    re : issue   
4           4     meter 7268 nov allocation   

                                             Message Spam/Ham        Date  
0                                                NaN      ham  1999-12-10  
1  gary , production from the high island larger ...      ham  1999-12-13  
2             - calpine daily gas nomination 1 . doc      ham  1999-12-14  
3  fyi - see note below - already done .\nstella\...      ham  1999-12-14  
4  fyi .\n- - - - - - - - - - - - - - - - - - - -...      ham  1999-12-14

In [50]:
df = df[~df['Message'].isna()]

In [51]:
label_list = list()

for label in df['Spam/Ham']:
  if label == 'spam':
    label_list.append(1)
  elif label == 'ham':
    label_list.append(0)

print(label_list)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [52]:
text_list = list()

for index in range(len(df)):
  text = str(df.iloc[index]['Subject']) + str(df.iloc[index]['Message'])
  text_list.append(text)

print(text_list[:5])

['vastar resources , inc .gary , production from the high island larger block a - 1 # 2 commenced on\nsaturday at 2 : 00 p . m . at about 6 , 500 gross . carlos expects between 9 , 500 and\n10 , 000 gross for tomorrow . vastar owns 68 % of the gross production .\ngeorge x 3 - 6992\n- - - - - - - - - - - - - - - - - - - - - - forwarded by george weissman / hou / ect on 12 / 13 / 99 10 : 16\nam - - - - - - - - - - - - - - - - - - - - - - - - - - -\ndaren j farmer\n12 / 10 / 99 10 : 38 am\nto : carlos j rodriguez / hou / ect @ ect\ncc : george weissman / hou / ect @ ect , melissa graves / hou / ect @ ect\nsubject : vastar resources , inc .\ncarlos ,\nplease call linda and get everything set up .\ni \' m going to estimate 4 , 500 coming up tomorrow , with a 2 , 000 increase each\nfollowing day based on my conversations with bill fischer at bmar .\nd .\n- - - - - - - - - - - - - - - - - - - - - - forwarded by daren j farmer / hou / ect on 12 / 10 / 99 10 : 34\nam - - - - - - - - - - - - - -

In [53]:
count_dict = dict()

for index, text in enumerate(text_list):
  if label_list[index] == 1:

    splited_text = text.split()

    for word in splited_text:
      if len(word) >= 3:
        if word in count_dict:
          count_dict[word] += 1
        else:
          count_dict[word] = 1

print(count_dict)

{'dobmeos': 1, 'with': 20344, 'hgh': 90, 'energy': 1518, 'level': 497, 'has': 7451, 'gone': 206, 'stukmintroducing': 1, 'doctor': 452, 'formulated': 66, 'human': 254, 'growth': 1259, 'hormone': 51, 'also': 2911, 'called': 311, 'referred': 72, 'medical': 730, 'science': 165, 'the': 107988, 'master': 165, 'very': 2349, 'plentiful': 6, 'when': 2515, 'are': 17256, 'young': 304, 'but': 4778, 'near': 436, 'age': 496, 'twenty': 327, 'one': 5960, 'our': 15901, 'bodies': 89, 'begin': 402, 'produce': 221, 'less': 968, 'time': 5516, 'forty': 60, 'nearly': 224, 'everyone': 392, 'deficient': 6, 'and': 74006, 'eighty': 37, 'production': 862, 'normally': 131, 'diminished': 7, 'least': 427, 'advantages': 93, 'increased': 475, 'muscle': 238, 'strength': 108, 'loss': 524, 'body': 685, 'fat': 343, 'bone': 65, 'density': 4, 'lower': 390, 'blood': 243, 'pressure': 104, 'quickens': 2, 'wound': 22, 'healing': 38, 'reduces': 47, 'cellulite': 31, 'improved': 182, 'vision': 146, 'wrinkle': 30, 'disappearance': 

In [54]:
sorted_count_dict = sorted(count_dict.items(), key= lambda item: item[1], reverse=True)[:500]

In [55]:
spam_words = list()

for word, count in sorted_count_dict:
  spam_words.append(word)

print(spam_words)

['the', 'and', 'you', 'this', 'for', 'your', 'that', 'with', 'are', 'from', 'our', 'not', 'have', 'will', 'com', 'all', 'company', 'can', 'http', 'email', 'more', 'here', 'information', 'any', 'has', 'please', 'statements', 'may', 'one', 'get', 'out', 'only', 'money', 'was', 'now', 'time', '000', 'business', 'www', 'new', 'mail', 'but', 'over', 'which', 'within', 'been', 'price', 'free', 'its', 'report', 'these', 'about', 'just', 'investment', 'other', 'account', 'click', 'make', 'their', 'they', 'message', 'future', 'inc', 'like', 'best', 'online', 'securities', 'software', 'stock', 'forward', 'into', 'what', 'through', 'need', 'looking', 'adobe', 'address', 'order', 'there', 'net', 'want', 'use', '2004', 'number', 'million', 'news', 'security', 'would', 'site', 'also', 'contact', '100', '2005', 'such', 'who', 'his', 'than', 'how', 'market', 'could', 'companies', 'many', 'products', 'send', 'made', 'gas', 'name', 'next', 'before', 'see', 'home', 'save', 'offer', 'act', 'today', 'when'

In [56]:
def check_spam_in_text(email, spam_words):
  vector = np.zeros((1, len(spam_words)), dtype=np.int32)

  splited_email = email.split()

  for index, word in enumerate(spam_words):
    if word in splited_email:
      vector[0, index] = 1

  return vector

In [57]:
sample = check_spam_in_text(text_list[21410], spam_words)

print(sample)

[[1 1 1 1 1 0 1 1 1 1 1 1 1 0 1 0 1 0 0 0 1 1 0 1 1 1 0 1 1 0 0 1 0 1 0 1
  0 0 0 0 0 1 0 1 0 1 1 0 1 1 0 0 0 1 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 1 0
  1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 1 1 1 1 0 0 0 0
  0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1 0 0
  0 0 1 0 0 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1
  0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 1 0 0 1 0 0 0
  0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 0
  0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1
  0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0
  0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0
  0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 

In [58]:
preprocessed_emails = np.empty((len(text_list), len(spam_words)), dtype=np.int32)

for index, email in enumerate(text_list):
  feature_vector = check_spam_in_text(email, spam_words)
  preprocessed_emails[index, :] = feature_vector

In [59]:
print(preprocessed_emails[:10])

[[1 1 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [1 1 0 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]]


In [60]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(preprocessed_emails, label_list,
                                                    test_size=0.2, shuffle=True, stratify=label_list)

In [61]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()
model.fit(X_train, y_train)

RandomForestClassifier()

In [62]:
train_preds = model.predict(X_train)
test_preds = model.predict(X_test)

In [63]:
from sklearn.metrics import accuracy_score

print(f'Train Accuracy: {accuracy_score(train_preds, y_train):.2f}')
print(f'Test Accuracy: {accuracy_score(test_preds, y_test):.2f}')

Train Accuracy: 1.00
Test Accuracy: 0.96
